
language: python

python:
  - "3.6"

jobs:
  include:
    - name: test
      services:
        - xvfb    # (X Virtual Framebuffer) to imitate a display, to run tests requiring GUI on Travis.
      before_script:
        - "export DISPLAY=:99.0"    # Display port to run xvfb on (VARIABLE=:PORT)
      install:
        # requirement for simpleaudio to work
        - sudo apt-get install libasound2-dev
        - pip install -qr requirements.txt
      script:
        - pycodestyle
        - python -m pytest
        - sh tests/scripts/test_examples.sh
        - sh tests/scripts/test_run_custom_classifier.sh
